# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import relay_pb2 as relay__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in relay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RelayStub(object):
    """Relay is the single gRPC service that mediates between workers and clients.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WorkerStream = channel.stream_stream(
                '/relay.v1.Relay/WorkerStream',
                request_serializer=relay__pb2.WorkerMessage.SerializeToString,
                response_deserializer=relay__pb2.WorkerCommand.FromString,
                _registered_method=True)
        self.TaskStream = channel.unary_stream(
                '/relay.v1.Relay/TaskStream',
                request_serializer=relay__pb2.TaskStreamRequest.SerializeToString,
                response_deserializer=relay__pb2.TaskMessage.FromString,
                _registered_method=True)
        self.UploadPayload = channel.unary_unary(
                '/relay.v1.Relay/UploadPayload',
                request_serializer=relay__pb2.UploadPayloadRequest.SerializeToString,
                response_deserializer=relay__pb2.UploadPayloadResponse.FromString,
                _registered_method=True)


class RelayServicer(object):
    """Relay is the single gRPC service that mediates between workers and clients.
    """

    def WorkerStream(self, request_iterator, context):
        """WorkerStream is a bidirectional stream — one per worker connection.
        Worker sends task output (stdout/stderr/metric/event/status).
        Relay sends back TypePayload commands when the client uploads encrypted data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStream(self, request, context):
        """TaskStream is a server-side stream — one per client × task subscription.
        The client receives backfilled and live messages for the requested task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPayload(self, request, context):
        """UploadPayload delivers the client's encrypted task payload to the worker.
        Replaces the former HTTP PUT /tasks/{task_id}/payload endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WorkerStream': grpc.stream_stream_rpc_method_handler(
                    servicer.WorkerStream,
                    request_deserializer=relay__pb2.WorkerMessage.FromString,
                    response_serializer=relay__pb2.WorkerCommand.SerializeToString,
            ),
            'TaskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=relay__pb2.TaskStreamRequest.FromString,
                    response_serializer=relay__pb2.TaskMessage.SerializeToString,
            ),
            'UploadPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPayload,
                    request_deserializer=relay__pb2.UploadPayloadRequest.FromString,
                    response_serializer=relay__pb2.UploadPayloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relay.v1.Relay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('relay.v1.Relay', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Relay(object):
    """Relay is the single gRPC service that mediates between workers and clients.
    """

    @staticmethod
    def WorkerStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/relay.v1.Relay/WorkerStream',
            relay__pb2.WorkerMessage.SerializeToString,
            relay__pb2.WorkerCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/relay.v1.Relay/TaskStream',
            relay__pb2.TaskStreamRequest.SerializeToString,
            relay__pb2.TaskMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/relay.v1.Relay/UploadPayload',
            relay__pb2.UploadPayloadRequest.SerializeToString,
            relay__pb2.UploadPayloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
