# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import relay_pb2 as relay__pb2


class RelayStub(object):
    """Relay is the single gRPC service that mediates between workers and clients.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WorkerStream = channel.stream_stream(
                '/relay.v1.Relay/WorkerStream',
                request_serializer=relay__pb2.WorkerMessage.SerializeToString,
                response_deserializer=relay__pb2.WorkerCommand.FromString,
                )
        self.TaskStream = channel.unary_stream(
                '/relay.v1.Relay/TaskStream',
                request_serializer=relay__pb2.TaskStreamRequest.SerializeToString,
                response_deserializer=relay__pb2.TaskMessage.FromString,
                )
        self.UploadPayload = channel.unary_unary(
                '/relay.v1.Relay/UploadPayload',
                request_serializer=relay__pb2.UploadPayloadRequest.SerializeToString,
                response_deserializer=relay__pb2.UploadPayloadResponse.FromString,
                )
        self.CancelTask = channel.unary_unary(
                '/relay.v1.Relay/CancelTask',
                request_serializer=relay__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=relay__pb2.CancelTaskResponse.FromString,
                )
        self.UploadResult = channel.unary_unary(
                '/relay.v1.Relay/UploadResult',
                request_serializer=relay__pb2.UploadResultRequest.SerializeToString,
                response_deserializer=relay__pb2.UploadResultResponse.FromString,
                )
        self.FetchResult = channel.unary_unary(
                '/relay.v1.Relay/FetchResult',
                request_serializer=relay__pb2.FetchResultRequest.SerializeToString,
                response_deserializer=relay__pb2.FetchResultResponse.FromString,
                )


class RelayServicer(object):
    """Relay is the single gRPC service that mediates between workers and clients.
    """

    def WorkerStream(self, request_iterator, context):
        """WorkerStream is a bidirectional stream — one per worker connection.
        Worker sends task output (stdout/stderr/metric/event/status).
        Relay sends back TypePayload commands when the client uploads encrypted data.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskStream(self, request, context):
        """TaskStream is a server-side stream — one per client × task subscription.
        The client receives backfilled and live messages for the requested task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPayload(self, request, context):
        """UploadPayload delivers the client's encrypted task payload to the worker.
        Replaces the former HTTP PUT /tasks/{task_id}/payload endpoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """CancelTask sends a cancel signal to the worker executing the given task.
        The client must present a valid relay_task_token scoped to that task_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadResult(self, request, context):
        """UploadResult stores the worker's encrypted task result in the relay's
        disk mailbox until the client fetches it (worker HMAC auth).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchResult(self, request, context):
        """FetchResult retrieves and deletes the stored result for a task
        (client bearer-token auth, scoped to the task_id).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WorkerStream': grpc.stream_stream_rpc_method_handler(
                    servicer.WorkerStream,
                    request_deserializer=relay__pb2.WorkerMessage.FromString,
                    response_serializer=relay__pb2.WorkerCommand.SerializeToString,
            ),
            'TaskStream': grpc.unary_stream_rpc_method_handler(
                    servicer.TaskStream,
                    request_deserializer=relay__pb2.TaskStreamRequest.FromString,
                    response_serializer=relay__pb2.TaskMessage.SerializeToString,
            ),
            'UploadPayload': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPayload,
                    request_deserializer=relay__pb2.UploadPayloadRequest.FromString,
                    response_serializer=relay__pb2.UploadPayloadResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=relay__pb2.CancelTaskRequest.FromString,
                    response_serializer=relay__pb2.CancelTaskResponse.SerializeToString,
            ),
            'UploadResult': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadResult,
                    request_deserializer=relay__pb2.UploadResultRequest.FromString,
                    response_serializer=relay__pb2.UploadResultResponse.SerializeToString,
            ),
            'FetchResult': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchResult,
                    request_deserializer=relay__pb2.FetchResultRequest.FromString,
                    response_serializer=relay__pb2.FetchResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'relay.v1.Relay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Relay(object):
    """Relay is the single gRPC service that mediates between workers and clients.
    """

    @staticmethod
    def WorkerStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/relay.v1.Relay/WorkerStream',
            relay__pb2.WorkerMessage.SerializeToString,
            relay__pb2.WorkerCommand.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TaskStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/relay.v1.Relay/TaskStream',
            relay__pb2.TaskStreamRequest.SerializeToString,
            relay__pb2.TaskMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadPayload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay.v1.Relay/UploadPayload',
            relay__pb2.UploadPayloadRequest.SerializeToString,
            relay__pb2.UploadPayloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay.v1.Relay/CancelTask',
            relay__pb2.CancelTaskRequest.SerializeToString,
            relay__pb2.CancelTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay.v1.Relay/UploadResult',
            relay__pb2.UploadResultRequest.SerializeToString,
            relay__pb2.UploadResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/relay.v1.Relay/FetchResult',
            relay__pb2.FetchResultRequest.SerializeToString,
            relay__pb2.FetchResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
