# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: relay.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'relay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brelay.proto\x12\x08relay.v1\"H\n\rWorkerMessage\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x01\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"H\n\rWorkerCommand\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x01\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"$\n\x11TaskStreamRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"S\n\x0bTaskMessage\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x01\x12\x0b\n\x03seq\x18\x04 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\"5\n\x14UploadPayloadRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x17\n\x15UploadPayloadResponse2\xe3\x01\n\x05Relay\x12\x44\n\x0cWorkerStream\x12\x17.relay.v1.WorkerMessage\x1a\x17.relay.v1.WorkerCommand(\x01\x30\x01\x12\x42\n\nTaskStream\x12\x1b.relay.v1.TaskStreamRequest\x1a\x15.relay.v1.TaskMessage0\x01\x12P\n\rUploadPayload\x12\x1e.relay.v1.UploadPayloadRequest\x1a\x1f.relay.v1.UploadPayloadResponseB\x1cZ\x1a\x63\x61s-relay/internal/relayv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'relay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032cas-relay/internal/relayv1'
  _globals['_WORKERMESSAGE']._serialized_start=25
  _globals['_WORKERMESSAGE']._serialized_end=97
  _globals['_WORKERCOMMAND']._serialized_start=99
  _globals['_WORKERCOMMAND']._serialized_end=171
  _globals['_TASKSTREAMREQUEST']._serialized_start=173
  _globals['_TASKSTREAMREQUEST']._serialized_end=209
  _globals['_TASKMESSAGE']._serialized_start=211
  _globals['_TASKMESSAGE']._serialized_end=294
  _globals['_UPLOADPAYLOADREQUEST']._serialized_start=296
  _globals['_UPLOADPAYLOADREQUEST']._serialized_end=349
  _globals['_UPLOADPAYLOADRESPONSE']._serialized_start=351
  _globals['_UPLOADPAYLOADRESPONSE']._serialized_end=374
  _globals['_RELAY']._serialized_start=377
  _globals['_RELAY']._serialized_end=604
# @@protoc_insertion_point(module_scope)
